### ISSUE TITLE
"Media URL (Invalid)" error on some URLs

### ISSUE THREAD

**Issue by hellpe** [NickvisionApps/TubeConverter#340]
Using the Flathub version on Fedora Silverblue 38

Although YouTube addresses work fine, URLs from [ina.fr](https://www.ina.fr/) seem to have stopped being recognized as valid. Feeding those to ytp-dl from the command line does work though.

```
$ flatpak --env=LANG=en_US run org.nickvision.tubeconverter
Python.Runtime.PythonException: 'formats'
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.GetItem(PyObject key)
   at Python.Runtime.PyObject.GetItem(String key)
   at Python.Runtime.PyObject.get_Item(String key)
   at NickvisionTubeConverter.Shared.Models.MediaUrlInfo.ParseFromPyDict(PyDict mediaInfo, Boolean isPartOfPlaylist) in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.Shared/Models/MediaUrlInfo.cs:line 112
   at NickvisionTubeConverter.Shared.Models.MediaUrlInfo.<>c__DisplayClass13_0.<GetAsync>b__0() in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.Shared/Models/MediaUrlInfo.cs:line 82
```

![image](https://github.com/NickvisionApps/TubeConverter/assets/1238320/0c30b02c-3355-4dbc-aaec-3c8f69e896bd)

**Comment by nlogozzo** [comment]
This was actually fixed with #335 .

Could you provide me with the URL you used so I can double check.

**Comment by nlogozzo** [comment]
Got it fixed, will be included in the next release :)
![image](https://github.com/NickvisionApps/TubeConverter/assets/17648453/521a9263-ad16-415b-a471-d99901242c8b)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/TubeConverter/releases/tag/2023.6.1-beta2

**Comment by taiwbi** [comment]
I still get this error on both `2023.7.3-beta` and `2023.7.2` installed from falthub :(

![Screenshot from 2023-07-22 10-18-05](https://github.com/NickvisionApps/Parabolic/assets/85298827/9a624d19-5986-4a0a-be44-c32a16cd3946)
![Screenshot from 2023-07-22 10-18-17](https://github.com/NickvisionApps/Parabolic/assets/85298827/6a52addc-0f25-4cd8-a42d-6c6ff3c65542)

**Comment by fsobolev** [comment]
@taiwbi any output when running in terminal?

**Comment by nlogozzo** [comment]
@taiwbi can you paste the link here so we can investigate it?

**Comment by fsobolev** [comment]
@nlogozzo https://www.youtube.com/watch?v=e74l3uPQLYc Works fine for me.

**Comment by nlogozzo** [comment]
Yeah works for me to in current stable:
![image](https://github.com/NickvisionApps/Parabolic/assets/17648453/6ab04eaf-8b6b-48ec-8884-f0f98217876c)

**Comment by taiwbi** [comment]
When I run it from terminal it works. The problem was that Youtube is blocked in my region and when I open application from apps grid, it doesn't follow system proxy settings.

I thought about it when I comment at first so I tried to download the video with VPN mode on [nekoray](https://github.com/MatsuriDayo/nekoray) which supposed to force proxy all the traffic but it didn't worked with that too :/

I fixed it by adding proxy variables for Parabolic on Flatseal.

```
all_proxy
HTTPS_PROXY
ALL_PROXY
https_proxy
HTTP_PROXY
http_proxy
no_proxy
NO_PROXY
ftp_proxy
FTP_PROXY
```
